import { Heart, Flame, Brain } from "lucide-react";

export const CONDITIONS = [
  {
    id: "CAD",
    name: "Коронарная болезнь сердца (CAD)",
    category: "Сердечно-сосудистые",
    icon: Heart,
    percentile: 93,
    sex: "M",
    age: 45,
    orPerSd: 1.62,
    individualOR: 2.08,
    prsZ: 1.27,
    tenYearRisk: 0.117,
    lifetimeRisk: 0.318,
    validatedAncestries: ["EUR", "EAS"],
    model: { pgsId: "PGS00XXXX", version: "1.3.2", genome: "GRCh38" },
    qc: { callRate: 0.988, imputed: true, snpCoverage: 0.94, ancestry: "EUR" },
  },
  {
    id: "T2D",
    name: "Сахарный диабет 2 типа (T2D)",
    category: "Метаболические",
    icon: Flame,
    percentile: 81,
    sex: "M",
    age: 45,
    orPerSd: 1.45,
    individualOR: 1.52,
    prsZ: 0.88,
    tenYearRisk: 0.082,
    lifetimeRisk: 0.366,
    validatedAncestries: ["EUR", "SAS", "AMR"],
    model: { pgsId: "PGS00YYYY", version: "2.1.0", genome: "GRCh38" },
    qc: { callRate: 0.983, imputed: true, snpCoverage: 0.91, ancestry: "EUR" },
  },
  {
    id: "CRC",
    name: "Колоректальный рак (CRC)",
    category: "Онкология",
    icon: Brain,
    percentile: 72,
    sex: "M",
    age: 45,
    orPerSd: 1.30,
    individualOR: 1.23,
    prsZ: 0.58,
    tenYearRisk: 0.021,
    lifetimeRisk: 0.073,
    validatedAncestries: ["EUR", "EAS", "AFR"],
    model: { pgsId: "PGS00ZZZZ", version: "0.9.7", genome: "GRCh38" },
    qc: { callRate: 0.991, imputed: false, snpCoverage: 0.97, ancestry: "EUR" },
  },
];

export const CATEGORY_COLORS = {
  "Сердечно-сосудистые": "from-rose-500/90 to-rose-400/70",
  Метаболические: "from-amber-500/90 to-amber-400/70",
  Онкология: "from-indigo-500/90 to-indigo-400/70",
};
